
# DS2002 — SQL + Python → Pandas DataFrames
## Studio — Working with DataFrames

This studio is designed to be completed **independently**.

You will:
- pull structured data from SQL into a DataFrame
- answer questions using Pandas (not SQL)
- practice filtering, sorting, grouping, and feature creation

The goal is not to memorize syntax.
The goal is to become comfortable *thinking with DataFrames*.


### Submission (Canvas)

1. Complete all TODOs below.
2. Run every cell so outputs are visible.
3. Save your Kaggle notebook.
4. Submit the **Kaggle Notebook GitHub URL** in Canvas.


## Part 0 — Setup (Run This Cell)

This cell prepares SQLite, Pandas, and helper functions.

In [24]:

import sqlite3
import pandas as pd

conn = sqlite3.connect(":memory:")

def exec_sql(sql):
    conn.executescript(sql)
    conn.commit()

def q(sql):
    return pd.read_sql_query(sql, conn)

print("Environment ready.")

Environment ready.


## Part 1 — Create and Load the Store Database (Provided)

Run the next cell to create tables and insert data.

In [25]:

exec_sql('''
CREATE TABLE customers (
    customer_id INTEGER PRIMARY KEY,
    name TEXT,
    region TEXT
);

CREATE TABLE products (
    product_id INTEGER PRIMARY KEY,
    name TEXT,
    category TEXT,
    price REAL
);

CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY,
    customer_id INTEGER,
    order_date TEXT
);

CREATE TABLE order_items (
    order_id INTEGER,
    product_id INTEGER,
    quantity INTEGER
);

INSERT INTO customers VALUES
(1,'Alice','East'),
(2,'Bob','West'),
(3,'Carol','East'),
(4,'David','South');

INSERT INTO products VALUES
(101,'Keyboard','Electronics',50),
(102,'Mouse','Electronics',20),
(103,'Monitor','Electronics',200),
(104,'Desk','Furniture',300),
(105,'Chair','Furniture',150);

INSERT INTO orders VALUES
(1,1,'2026-02-01'),
(2,2,'2026-02-02'),
(3,1,'2026-02-03'),
(4,3,'2026-02-03'),
(5,4,'2026-02-04');

INSERT INTO order_items VALUES
(1,101,1),(1,102,2),
(2,103,1),
(3,104,1),(3,105,1),
(4,101,2),(4,103,1),
(5,105,2);
''')

print("Store data loaded.")

Store data loaded.


## Part 2 — Pull Data into a DataFrame

You will use **one SQL query** to create a DataFrame.
After this point, **do not use SQL** to answer questions.

In [26]:

df = q('''
SELECT
    c.name AS customer,
    c.region,
    o.order_id,
    o.order_date,
    p.name AS product,
    p.category,
    oi.quantity,
    p.price,
    (oi.quantity * p.price) AS line_total
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
ORDER BY o.order_date;
''')

df

,customer,region,order_id,order_date,product,category,quantity,price,line_total
0,Alice,East,1,2026-02-01,Keyboard,Electronics,1,50.0,50.0
1,Alice,East,1,2026-02-01,Mouse,Electronics,2,20.0,40.0
2,Bob,West,2,2026-02-02,Monitor,Electronics,1,200.0,200.0
3,Alice,East,3,2026-02-03,Desk,Furniture,1,300.0,300.0
4,Alice,East,3,2026-02-03,Chair,Furniture,1,150.0,150.0
5,Carol,East,4,2026-02-03,Keyboard,Electronics,2,50.0,100.0
6,Carol,East,4,2026-02-03,Monitor,Electronics,1,200.0,200.0
7,David,South,5,2026-02-04,Chair,Furniture,2,150.0,300.0


## Part 3 — DataFrame Questions

Answer each question using **Pandas operations only**.

### Q1. How many rows and columns are in the DataFrame?

In [27]:

# TODO
df.shape

(8, 9)

### Q2. List the column names and their data types.

In [28]:

# TODO
df.dtypes

customer       object
region         object
order_id        int64
order_date     object
product        object
category       object
quantity        int64
price         float64
line_total    float64
dtype: object

### Q3. Show only the rows where the customer is Alice.

In [29]:

# TODO
df[df['customer'] == 'Alice']

,customer,region,order_id,order_date,product,category,quantity,price,line_total
0,Alice,East,1,2026-02-01,Keyboard,Electronics,1,50.0,50.0
1,Alice,East,1,2026-02-01,Mouse,Electronics,2,20.0,40.0
3,Alice,East,3,2026-02-03,Desk,Furniture,1,300.0,300.0
4,Alice,East,3,2026-02-03,Chair,Furniture,1,150.0,150.0

### Q4. Show all line items with a line total greater than $100.

In [30]:

# TODO
df[df['line_total'] > 100]

,customer,region,order_id,order_date,product,category,quantity,price,line_total
2,Bob,West,2,2026-02-02,Monitor,Electronics,1,200.0,200.0
3,Alice,East,3,2026-02-03,Desk,Furniture,1,300.0,300.0
4,Alice,East,3,2026-02-03,Chair,Furniture,1,150.0,150.0
6,Carol,East,4,2026-02-03,Monitor,Electronics,1,200.0,200.0
7,David,South,5,2026-02-04,Chair,Furniture,2,150.0,300.0

### Q5. Sort the DataFrame by line_total from highest to lowest.

In [31]:

# TODO
df.sort_values('line_total', ascending=False)

,customer,region,order_id,order_date,product,category,quantity,price,line_total
3,Alice,East,3,2026-02-03,Desk,Furniture,1,300.0,300.0
7,David,South,5,2026-02-04,Chair,Furniture,2,150.0,300.0
6,Carol,East,4,2026-02-03,Monitor,Electronics,1,200.0,200.0
2,Bob,West,2,2026-02-02,Monitor,Electronics,1,200.0,200.0
4,Alice,East,3,2026-02-03,Chair,Furniture,1,150.0,150.0
5,Carol,East,4,2026-02-03,Keyboard,Electronics,2,50.0,100.0
0,Alice,East,1,2026-02-01,Keyboard,Electronics,1,50.0,50.0
1,Alice,East,1,2026-02-01,Mouse,Electronics,2,20.0,40.0

### Q6. Create a new column called tax (7% of line_total).

In [32]:

# TODO
df['tax'] = df['line_total'] * 0.07

df.head()

,customer,region,order_id,order_date,product,category,quantity,price,line_total,tax
0,Alice,East,1,2026-02-01,Keyboard,Electronics,1,50.0,50.0,3.5
1,Alice,East,1,2026-02-01,Mouse,Electronics,2,20.0,40.0,2.8
2,Bob,West,2,2026-02-02,Monitor,Electronics,1,200.0,200.0,14.0
3,Alice,East,3,2026-02-03,Desk,Furniture,1,300.0,300.0,21.0
4,Alice,East,3,2026-02-03,Chair,Furniture,1,150.0,150.0,10.5

### Q7. Create a new column called total_with_tax.

In [33]:

# TODO
df['total_with_tax'] = df['line_total'] + df['tax']

df.head()

,customer,region,order_id,order_date,product,category,quantity,price,line_total,tax,total_with_tax
0,Alice,East,1,2026-02-01,Keyboard,Electronics,1,50.0,50.0,3.5,53.5
1,Alice,East,1,2026-02-01,Mouse,Electronics,2,20.0,40.0,2.8,42.8
2,Bob,West,2,2026-02-02,Monitor,Electronics,1,200.0,200.0,14.0,214.0
3,Alice,East,3,2026-02-03,Desk,Furniture,1,300.0,300.0,21.0,321.0
4,Alice,East,3,2026-02-03,Chair,Furniture,1,150.0,150.0,10.5,160.5

### Q8. What is the total revenue per customer?

In [34]:

# TODO
df.groupby('customer', as_index=False)['line_total'].sum().rename(columns={'line_total':'total_revenue'})

  customer  total_revenue
0    Alice          540.0
1      Bob          200.0
2    Carol          300.0
3    David          300.0

### Q9. What is the average line_total per product category?

In [35]:

# TODO
df.groupby('category', as_index=False)['line_total'].mean().rename(columns={'line_total':'avg_line_total'})

      category  avg_line_total
0  Electronics           118.0
1    Furniture           250.0

### Q10. Which customer spent the most overall?

In [36]:

# TODO
df.groupby('customer')['line_total'].sum().idxmax()

'Alice'

### Q11. Which region generated the most revenue?

In [37]:

# TODO
df.groupby('region')['line_total'].sum().idxmax()

'East'

### Q12. Create a summary DataFrame with customer and total_spent.

In [38]:

# TODO
customer_summary = (df.groupby('customer', as_index=False)['line_total']
                    .sum()
                    .rename(columns={'line_total':'total_spent'}))

customer_summary

  customer  total_spent
0    Alice        540.0
1      Bob        200.0
2    Carol        300.0
3    David        300.0

### Q13. Write that summary DataFrame back to the database as customer_summary.

In [39]:

# TODO
customer_summary.to_sql('customer_summary', conn, if_exists='replace', index=False)

q('SELECT * FROM customer_summary')

  customer  total_spent
0    Alice        540.0
1      Bob        200.0
2    Carol        300.0
3    David        300.0


## Part 4 — Reflection

In 2–3 sentences:
- What DataFrame operation felt most intuitive?
- What still feels confusing?

In [40]:

reflection = """
I think that groupby was the most intuitive because it's basically just filtering.
To me, remembering all the possible arguments that each operation takes and when to use each one  can be a little confusing
"""

print(reflection)

I think that groupby was the most intuitive because it's basically just filtering.
To me, remembering all the possible arguments that each operation takes and when to use each one  can be a little confusing


## You Are Done

Make sure:
- all TODOs are completed
- all cells run without error
- outputs are visible

Then submit your Kaggle Notebook Github URL in Canvas to me and Daniel